### ISSUE TITLE
Potential Issue with using DQMH

### ISSUE THREAD

**Issue by qalldredge** [jacobson3/VI-Peek#13]
This becomes a problem when creating LabVIEW IDE add-ons no matter what framework you use.  There is the potential that you lock up classes or libraries of the framework.  This is due to the libraries being used in your instance as used by the add-on tool and also in use by a developer using your tool while developing their own code using those libraries.  

There are two workarounds:

1. Don't use the frameworks/libraries
2. Make sure when your tool is deployed (via a package or otherwise) that a different namespaced copy of the framework code is installed for use of your tool.

I have had to remove instances of Actor Framework and MGI's Panel Manager from some of my IDE add-ons for this reason.

**Comment by jacobson3** [comment]
This is good to keep in mind but do you think that this will even effect people using the DQMH framework? My understanding is that this would cause the DQMH classes to be locked to editing but is that something that DQMH users would need to do? I'm not a DQMH power user but from my experience these classes just sit in my dependencies so I'm not sure being locked is an issue.

**Comment by qalldredge** [comment]
You are right.  This should only cause locking of the underlying DQMH classes.  Everything else should be fine.

**Comment by jacobson3** [comment]
I'm in the process of creating a package build and I've added DQMH as a dependency so those files should be present when installed as well.
