### ISSUE TITLE
Window placement and sizing.

### ISSUE THREAD

**Issue by qalldredge** [jacobson3/VI-Peek#15]
I'm not sure if the window placement and sizing should be done how it is now.  Sometimes the resizing places the title bar off of the screen to the top (if close to the top of the screen and opening a large Block Diagram).  

Options could include:

* the top-left corner should be set and resizing is done down and to the right (similar to the Context Help window) with some maximum
* the size/position is set and remembered from run-to-run (similar to Quick Drop window)
* continue to popup by the selected VI but don't automatically resize for the Block Diagram, ensure doesn't leave the top of the screen
* resize how you originally planned, resizing to the VIs previously saved size (Is this available to read somewhere?) but ensure doesn't leave the screen
* some other way I haven't thought of

**Comment by jacobson3** [comment]
@qalldredge I created a Window-Resize branch which implements the second bullet point (and made a few small changes to make sure the window hides when it should). Let me know if this window behavior is better than what we currently have.

**Comment by qalldredge** [comment]
@jacobson3 I think I like this better.  Then it's not always moving and shifting around.
