### ISSUE TITLE
Error When Selecting Missing VI

### ISSUE THREAD

**Issue by jacobson3** [jacobson3/VI-Peek#16]
If you try to click a missing VI, you will receive the following error.

Error 1 occurred at Open VI Reference in Peek Window.lvlib:Insert Into Subpanel.vi->Peek Window.lvlib:Main.vi

**Comment by qalldredge** [comment]
Hopefully, this is fixed with the merging of my OO branch. Check it out and if you think it is sufficient, my recommendation is to close this issue.

**Comment by jacobson3** [comment]
When I was trying it out I think you handled the case well when a user clicked on a missing VI when it was inside of the peek window but I think it may still error out when it is the top level VI.

**Comment by jacobson3** [comment]
Okay this does seem to generally work but the missing VI seems to mangle the peek stack which led to some lockups from my testing (it also doesn't always react to a selection). Note that when the gif below ends the peek window essentially seems to be locked up.
![missingVI](https://user-images.githubusercontent.com/25009788/132746110-0ec49b8b-a1ec-470f-894b-ab985698fd35.gif)
