### ISSUE TITLE
Improve Malleable VI Naming

### ISSUE THREAD

**Issue by jacobson3** [jacobson3/VI-Peek#17]
If you select a malleable VI it will open up the standard VI (the implementation given the input data types) but this results in the malleable VI using a nonsense name as shown below.

2f4716db-bacd-4fb1-89da-d0e816fd5f11.vi

Ideally we can get that to show up as <malleable_name>.vim. The above VI name is correct but not actually helpful to users.

**Comment by qalldredge** [comment]
I did not find an easy way to correlate the instance name back to the actual name but I did find a way.  Should I replace the instance name with the actual name in the stack entirely or just as it shows in the tree?  This will have the effect of showing and opening the actual VIM and not the instance in the subpanel.  Or should we show the instance? Or should we allow both similar to the dynamic dispatch VIs?

**Comment by jacobson3** [comment]
Personally I would want to show the specific instance but have the name appear as it would on disk (like malleable_function.vim).

**Comment by qalldredge** [comment]
I don't know.  It might be nice showing the instance but it might be confusing.  The instance code is usually not visible unless you convert the instance into a Standard VI and then it ceases being a Malleable VI.  Also, you shouldn't open and try to edit the instance code.  I think it should either be the Actual VIM only or we should have some way to have both but the instance should not be openable.

**Comment by qalldredge** [comment]
Hopefully, this is fixed with the merging of my OO branch.  Check it out and if you this it is sufficient, my recommendation is to close this issue.

**Comment by jacobson3** [comment]
I think you're right, I'll double check this.

**Comment by jacobson3** [comment]
You're correct, this was resolved in #21
