### ISSUE TITLE
Ctrl+Shift+N doesn't always toggle peek visibility

### ISSUE THREAD

**Issue by negentropicdev** [jacobson3/VI-Peek#24]
Self explanatory. I understand that there are separate start and stop methods but they could both be made to call the same vi which checks the current state and launches as necessary or triggers the close.

**Comment by jacobson3** [comment]
I think that makes sense and shouldn't be too difficult. We should be able to check if the module is running and just run the open method if it's not running and the close method if it is running, regardless of the "open" input.
