### ISSUE TITLE
Add functionality to deal with Dynamic Dispatch VIs in a LabVIEW Class.

### ISSUE THREAD

**Issue by qalldredge** [jacobson3/VI-Peek#7]
When clicking on a SubVI that is LabVIEW Class Dynamic Dispatch VI, prompt the user for the Dynamic instance to show.  This should be similar to what the user sees when double-clicking on the SubVI and the selection window pops up showing a tree and BD views.

**Comment by qalldredge** [comment]
Maybe there is a way to call the already created "Choose Implementation" dialog.  It is located at: 

_[LabVIEW 20xx]\resource\Framework\Providers\LVClassLibrary\ChooseImplementation\CLSUIP_ChooseImplementationDialog.vi_

**Comment by qalldredge** [comment]
Looking into the "Choose Implementation" dialog, it doesn't return the VI(s) selected.  It opens the VI(s) directly from the dialog.  So we can't call it directly to have VI Peek know which VI to load into its subpanel.  However, maybe I can reuse some of the code to implement our own version of it.

**Comment by qalldredge** [comment]
So, I have it working on my fork.  If the VI dynamic dispatch, my version of the "Choose Implementation" dialog opens.  Then it allows selection and passes the selection back to the VI Peek window.  I'm not sure I like this extra step.  I think it would be better if I implemented the "Choose Implementation" functionality directly into the VI Peek window.

Feel free to take a look at my implementation but it is rough.  Some of the "Choose Implementation" dialog functionality from the built-in LabVIEW one still needs to be removed.  But if I combine it with the VI Peek windows I'll do that anyway.

**Comment by jacobson3** [comment]
Added in #14
